// Copies the `abi` field of the compiled Foundry artifacts into src/lib/abis/<Name>.ts.
// Usage: pnpm sync-abis   (expects ../contracts/out to exist; run `forge build` there first)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "..", "..", "contracts", "out");
const destDir = resolve(here, "..", "src", "lib", "abis");

const NAMES = [
  "Factory",
  "Token",
  "FeeEscrow",
  "AnchorRegistry",
  "LaunchAndBuyRouter",
  "TickerLauncher",
  "TickerToken",
  "CoinQuoteLauncher",
  "StockQuoteLauncher",
  "MarketQuoteLauncher",
  "LaunchDeployer",
  "ZapRouter",
  "LaunchSeeder",
  "LaunchLocker",
];

mkdirSync(destDir, { recursive: true });
const written = [];
for (const name of NAMES) {
  const src = join(outDir, `${name}.sol`, `${name}.json`);
  if (!existsSync(src)) {
    console.warn(`skip ${name}: ${src} not found`);
    continue;
  }
  const { abi } = JSON.parse(readFileSync(src, "utf8"));
  const body =
    `// Generated by scripts/sync-abis.mjs from contracts/out/${name}.sol/${name}.json. Do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(destDir, `${name}.ts`), body);
  written.push(name);
}

// the coin's creation bytecode, so the create page can grind a CREATE2 salt for a vanity address without any RPC call
{
  const tokenArtifact = join(outDir, "Token.sol", "Token.json");
  if (existsSync(tokenArtifact)) {
    const { bytecode } = JSON.parse(readFileSync(tokenArtifact, "utf8"));
    const code = bytecode.object.startsWith("0x") ? bytecode.object : `0x${bytecode.object}`;
    writeFileSync(
      resolve(destDir, "..", "tokenBytecode.ts"),
      `// Generated by scripts/sync-abis.mjs from contracts/out/Token.sol/Token.json. Do not edit.\n` +
        `// The creation code of every coin launched through the factory. Its hash, with the constructor arguments, fixes the\n` +
        `// CREATE2 address, which is how the create page grinds a salt for an address ending in 6942.\n` +
        `export const TOKEN_CREATION_CODE = "${code}" as const;\n`,
    );
    console.log("wrote src/lib/tokenBytecode.ts");
  }
}
writeFileSync(
  join(destDir, "index.ts"),
  `// Generated by scripts/sync-abis.mjs. Do not edit.\n` +
    written.map((n) => `export { ${n}Abi } from "./${n}";`).join("\n") +
    "\n",
);
console.log(`wrote ${written.length} ABIs to ${destDir}`);
